
---
development:
  options: ~
  sessions:
    default:
      database: smon-development
      hosts:
        - "localhost:27017"
      options:
        autocreate_indexes: true
        allow_dynamic_fields: true
        include_root_in_json: false
        parameterize_keys: true
        persist_in_safe_mode: false
        raise_not_found_error: true
        skip_version_check: true
        safe: true
        reconnect_time: 3
test:
  sessions:
    default:
      database: smon-test
      hosts:
        - "localhost:27017"
      options:
        autocreate_indexes: true
        allow_dynamic_fields: true
        include_root_in_json: false
        parameterize_keys: true
        persist_in_safe_mode: false
        raise_not_found_error: true
        skip_version_check: true
        safe: true
        reconnect_time: 3
production:
  sessions:
    default:
      database: smon-production
      hosts:
        - "localhost:27017"
      options:
        autocreate_indexes: true
        allow_dynamic_fields: true
        include_root_in_json: false
        parameterize_keys: true
        persist_in_safe_mode: false
        raise_not_found_error: true
        skip_version_check: true
        safe: true
        reconnect_time: 3
