defaults: &defaults
  hosts:
    - localhost
  autocreate_indexes: true
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  skip_version_check: true
  safe: true
  reconnect_time: 3

development:
  sessions:
    default:
      <<: *defaults
      database: smon-development


test:
  sessions:
    default:
      <<: *defaults
      database: smon-test

production:
  sessions:
    default:
      <<: *defaults
      database: smon-production
